name: crypto_tds_ledger_india
description: TDS App
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  pdf: ^3.10.4
  printing: ^5.11.0
  csv: ^5.0.2
  path_provider: ^2.0.11
  share_plus: ^7.2.1

flutter:
  uses-material-design: true
